<#
.SYNOPSIS
    Update path references from old to new folder names
    
.DESCRIPTION
    Batch updates path references based on the CSV generated by Find-PathReferences.ps1.
    Requires manual review and confirmation before making changes.
    
    This addresses Moderate Issue #5: Impact analysis and batch path updates
    
.PARAMETER PortfolioRoot
    Path to the portfolio root (default: C:\Portfolio)
    
.PARAMETER CsvPath
    Path to CSV file from Find-PathReferences.ps1
    
.PARAMETER DryRun
    Preview changes without applying them
    
.PARAMETER Force
    Skip confirmation prompts (use with extreme caution!)
    
.EXAMPLE
    .\Update-PathReferences.ps1 -DryRun
    Preview what would be updated
    
.EXAMPLE
    .\Update-PathReferences.ps1
    Update path references with confirmation prompts
    
.NOTES
    IMPORTANT: Always run Find-PathReferences.ps1 first and review the CSV!
    This script modifies files - ensure you have backups and git commits.
#>

[CmdletBinding()]
param(
    [Parameter()]
    [string]$PortfolioRoot = "C:\Portfolio",
    
    [Parameter()]
    [string]$CsvPath,
    
    [Parameter()]
    [switch]$DryRun,
    
    [Parameter()]
    [switch]$Force
)

#Requires -Version 5.1

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

# Set default CSV path
if (-not $CsvPath) {
    $CsvPath = Join-Path $PortfolioRoot ".path-references-found.csv"
}

# Color output functions
function Write-Step {
    param([string]$Message)
    Write-Host "`n==> " -ForegroundColor Cyan -NoNewline
    Write-Host $Message -ForegroundColor White
}

function Write-Success {
    param([string]$Message)
    Write-Host "    ✓ " -ForegroundColor Green -NoNewline
    Write-Host $Message -ForegroundColor White
}

function Write-Warning {
    param([string]$Message)
    Write-Host "    ⚠ " -ForegroundColor Yellow -NoNewline
    Write-Host $Message -ForegroundColor Yellow
}

function Write-ErrorMsg {
    param([string]$Message)
    Write-Host "    ✗ " -ForegroundColor Red -NoNewline
    Write-Host $Message -ForegroundColor Red
}

function Write-Info {
    param([string]$Message)
    Write-Host "    ℹ " -ForegroundColor Blue -NoNewline
    Write-Host $Message -ForegroundColor Gray
}

# Statistics
$script:Stats = @{
    FilesProcessed = 0
    ReferencesUpdated = 0
    Errors = 0
}

# Load CSV
function Import-PathReferences {
    Write-Step "Loading path references from CSV..."
    
    if (-not (Test-Path $CsvPath)) {
        Write-ErrorMsg "CSV file not found: $CsvPath"
        Write-Info "Run Find-PathReferences.ps1 first to generate the CSV"
        exit 1
    }
    
    try {
        $references = Import-Csv -Path $CsvPath -Encoding UTF8
        Write-Success "Loaded $($references.Count) path references"
        return $references
    } catch {
        Write-ErrorMsg "Could not load CSV: $_"
        exit 1
    }
}

# Group references by file
function Get-UpdatesByFile {
    param([array]$References)
    
    $grouped = $References | Group-Object -Property FilePath
    
    Write-Info "References span $($grouped.Count) files"
    
    return $grouped
}

# Update file with path replacements
function Update-FileReferences {
    param(
        [string]$RelativeFilePath,
        [array]$Updates
    )
    
    $fullPath = Join-Path $PortfolioRoot $RelativeFilePath
    
    if (-not (Test-Path $fullPath)) {
        Write-Warning "File not found: $RelativeFilePath"
        $script:Stats.Errors++
        return $false
    }
    
    try {
        # Read file content
        $content = Get-Content -Path $fullPath -Raw -Encoding UTF8
        $originalContent = $content
        $updateCount = 0
        
        # Apply each update
        foreach ($update in $Updates) {
            $oldPath = $update.OldPath
            $newPath = $update.SuggestedNewPath
            
            if (-not $newPath) {
                Write-Warning "No suggested path for: $oldPath (skipping)"
                continue
            }
            
            # Replace all occurrences (case-insensitive)
            $pattern = [regex]::Escape($oldPath)
            if ($content -match $pattern) {
                $content = $content -replace $pattern, $newPath
                $updateCount++
            }
        }
        
        # Check if content changed
        if ($content -ne $originalContent) {
            if ($DryRun) {
                Write-Info "[DRY RUN] Would update: $RelativeFilePath ($updateCount replacements)"
            } else {
                # Write updated content
                Set-Content -Path $fullPath -Value $content -Encoding UTF8 -NoNewline
                Write-Success "Updated: $RelativeFilePath ($updateCount replacements)"
            }
            
            $script:Stats.FilesProcessed++
            $script:Stats.ReferencesUpdated += $updateCount
            return $true
        } else {
            Write-Info "No changes needed: $RelativeFilePath"
            return $false
        }
        
    } catch {
        Write-ErrorMsg "Error updating $RelativeFilePath : $_"
        $script:Stats.Errors++
        return $false
    }
}

# Show preview
function Show-UpdatePreview {
    param([array]$GroupedUpdates)
    
    Write-Step "Preview of updates"
    
    $totalFiles = $GroupedUpdates.Count
    $totalRefs = ($GroupedUpdates | ForEach-Object { $_.Group.Count } | Measure-Object -Sum).Sum
    
    Write-Host ""
    Write-Host "  Files to update:      " -NoNewline
    Write-Host $totalFiles -ForegroundColor White
    Write-Host "  Total replacements:   " -NoNewline
    Write-Host $totalRefs -ForegroundColor White
    Write-Host ""
    
    # Show sample of files
    Write-Host "  Sample files (first 10):" -ForegroundColor Cyan
    $sample = $GroupedUpdates | Select-Object -First 10
    
    foreach ($group in $sample) {
        $refCount = $group.Group.Count
        Write-Host "    • " -ForegroundColor Yellow -NoNewline
        Write-Host "$($group.Name)" -ForegroundColor Gray -NoNewline
        Write-Host " ($refCount replacements)" -ForegroundColor Gray
    }
    
    if ($totalFiles -gt 10) {
        Write-Host "    ... and $($totalFiles - 10) more files" -ForegroundColor Gray
    }
    
    Write-Host ""
}

# Create git checkpoint
function New-GitCheckpoint {
    param([string]$Message)
    
    if ($DryRun) {
        Write-Info "[DRY RUN] Would create git checkpoint: $Message"
        return
    }
    
    Push-Location $PortfolioRoot
    try {
        git rev-parse --git-dir 2>&1 | Out-Null
        if ($LASTEXITCODE -eq 0) {
            git add -A
            git commit -m "Migration - Checkpoint: $Message" -m "Automated path reference updates"
            Write-Success "Git checkpoint created: $Message"
        }
    } catch {
        Write-Warning "Could not create git checkpoint: $_"
    } finally {
        Pop-Location
    }
}

# Main execution
function Start-PathUpdates {
    Write-Host ""
    Write-Host "═══════════════════════════════════════════════════════════════" -ForegroundColor Cyan
    Write-Host "  Update Path References - Batch Path Updates                " -ForegroundColor Cyan
    Write-Host "═══════════════════════════════════════════════════════════════" -ForegroundColor Cyan
    Write-Host ""
    
    if ($DryRun) {
        Write-Warning "DRY RUN MODE - No changes will be made"
        Write-Host ""
    }
    
    # Load references
    $references = Import-PathReferences
    
    if ($references.Count -eq 0) {
        Write-Info "No path references to update"
        exit 0
    }
    
    # Group by file
    $grouped = Get-UpdatesByFile -References $references
    
    # Show preview
    Show-UpdatePreview -GroupedUpdates $grouped
    
    # Confirmation
    if (-not $DryRun -and -not $Force) {
        Write-Warning "This will modify $($grouped.Count) files in your portfolio!"
        Write-Warning "Ensure you have:"
        Write-Host "  1. Reviewed the CSV file" -ForegroundColor Yellow
        Write-Host "  2. Created a backup (Backup-PortfolioMeta.ps1)" -ForegroundColor Yellow
        Write-Host "  3. Committed current changes to git" -ForegroundColor Yellow
        Write-Host ""
        
        $response = Read-Host "Proceed with path updates? (y/N)"
        if ($response -ne 'y' -and $response -ne 'Y') {
            Write-Info "Cancelled by user"
            exit 0
        }
    }
    
    # Create checkpoint before updates
    New-GitCheckpoint -Message "Before path reference updates"
    
    # Process updates
    Write-Step "Updating path references..."
    
    $progress = 0
    $total = $grouped.Count
    
    foreach ($fileGroup in $grouped) {
        $progress++
        
        if ($progress % 10 -eq 0 -or $progress -eq $total) {
            Write-Progress -Activity "Updating files" -Status "$progress of $total" -PercentComplete (($progress / $total) * 100)
        }
        
        Update-FileReferences -RelativeFilePath $fileGroup.Name -Updates $fileGroup.Group
    }
    
    Write-Progress -Activity "Updating files" -Completed
    
    # Create checkpoint after updates
    if (-not $DryRun) {
        New-GitCheckpoint -Message "After path reference updates"
    }
    
    # Summary
    Write-Host ""
    Write-Host "═══════════════════════════════════════════════════════════════" -ForegroundColor Cyan
    Write-Host "  Update Summary                                              " -ForegroundColor Cyan
    Write-Host "═══════════════════════════════════════════════════════════════" -ForegroundColor Cyan
    Write-Host ""
    
    Write-Host "  Files processed:      " -NoNewline
    Write-Host $script:Stats.FilesProcessed -ForegroundColor Green
    Write-Host "  References updated:   " -NoNewline
    Write-Host $script:Stats.ReferencesUpdated -ForegroundColor Green
    
    if ($script:Stats.Errors -gt 0) {
        Write-Host "  Errors encountered:   " -NoNewline
        Write-Host $script:Stats.Errors -ForegroundColor Red
    }
    
    Write-Host ""
    
    if ($DryRun) {
        Write-Host "═══════════════════════════════════════════════════════════════" -ForegroundColor Yellow
        Write-Warning "DRY RUN - No actual changes were made"
        Write-Host "═══════════════════════════════════════════════════════════════" -ForegroundColor Yellow
        Write-Host ""
        Write-Info "Review the preview above, then run without -DryRun to apply changes"
    } else {
        Write-Host "═══════════════════════════════════════════════════════════════" -ForegroundColor Green
        Write-Success "Path updates completed!"
        Write-Host "═══════════════════════════════════════════════════════════════" -ForegroundColor Green
        Write-Host ""
        Write-Info "Next steps:"
        Write-Info "1. Review git diff to verify changes"
        Write-Info "2. Test that links/paths work correctly"
        Write-Info "3. Run Test-MigrationSuccess.ps1 to validate"
        Write-Host ""
    }
}

# Execute
Start-PathUpdates
